INSERT INTO tbl_cards (hp, name, type_id, stage_id, info, attack, damage, weak, resist, retreat, cardNumberInCollection, collection_id)
VALUES 
(50, 'Charmander', 1, 1, 'Prefers hot places. Spits fire occasionally.', 'Ember', '40', 'Water x2', 'None', 1, 4, 1),
(40, 'Caterpie', 3, 1, 'Releases a strong odor from its antennae.', 'Tackle', '10', 'Fire x2', 'None', 1, 32, 1),
(70, 'Butterfree', 3, 2, 'Flits about to spread pollen.', 'Confusion', '30', 'Fire x2', 'Grass -30', 1, 33, 1),
(60, 'Beedrill', 3, 2, 'Flies fast and attacks with its sharp stingers.', 'Twineedle', '40', 'Fire x2', 'Grass -30', 0, 17, 1),
(80, 'Nidoking', 6, 2, 'Its thick tail packs a powerful punch.', 'Thrash', '60', 'Psychic x2', 'None', 2, 34, 1),
(50, 'Clefairy', 7, 1, 'Often found dancing in moonlight.', 'Sing', '10', 'Darkness x2', 'None', 1, 5, 2),
(40, 'Vulpix', 1, 1, 'Its six tails become more beautiful as it grows.', 'Fire Blast', '50', 'Water x2', 'None', 1, 68, 2),
(60, 'Poliwag', 2, 1, 'Its thin membrane is clearly visible.', 'Bubblebeam', '30', 'Electric x2', 'None', 1, 72, 2),
(100, 'Nidoqueen', 6, 2, 'Its body is covered with hard scales.', 'Earthquake', '90', 'Psychic x2', 'None', 3, 8, 1),
(70, 'Kadabra', 5, 2, 'Able to bend spoons with its psychic energy.', 'Psybeam', '50', 'Darkness x2', 'None', 1, 57, 1),
(40, 'Oddish', 3, 1, 'Wanders at night to soak up moonlight.', 'Absorb', '20', 'Fire x2', 'Grass -20', 1, 48, 1),
(60, 'Gloom', 3, 2, 'Its noxious pollen triggers coughing fits.', 'Poisonpowder', '30', 'Fire x2', 'Grass -20', 2, 49, 1),
(40, 'Psyduck', 2, 1, 'Always looks confused due to chronic headaches.', 'Water Gun', '30', 'Electric x2', 'None', 1, 54, 2),
(90, 'Dewgong', 2, 2, 'Nimbly swims through ice-cold waters.', 'Aurora Beam', '80', 'Electric x2', 'Fire -30', 2, 17, 2),
(60, 'Grimer', 6, 1, 'Sludge Pokémon that leaves filth in its wake.', 'Poison Gas', '20', 'Psychic x2', 'None', 1, 69, 2),
(80, 'Muk', 6, 2, 'Larger and stronger than Grimer.', 'Sludge Bomb', '60', 'Psychic x2', 'None', 2, 70, 2),
(70, 'Exeggutor', 3, 2, 'Each head has its own thinking process.', 'Stomp', '40', 'Fire x2', 'Grass -20', 3, 34, 2),
(60, 'Cubone', 6, 1, 'Wears the skull of its deceased mother.', 'Bone Club', '40', 'Water x2', 'None', 2, 50, 2),
(100, 'Rhydon', 6, 2, 'Evolves by practicing its rock-hard charging.', 'Horn Drill', '80', 'Water x2', 'Electric -20', 4, 45, 2),
(70, 'Koffing', 6, 1, 'Contains toxic gases in its body.', 'Smog', '20', 'Psychic x2', 'None', 1, 77, 3),
(40, 'Rhyhorn', 6, 1, 'Its rock-like body is tough to damage.', 'Stomp', '30', 'Water x2', 'None', 2, 111, 3),
(60, 'Electabuzz', 4, 1, 'Electricity courses through its body.', 'Thunderpunch', '50', 'Fighting x2', 'None', 2, 36, 3),
(70, 'Magmar', 1, 1, 'Its fiery body can scorch everything.', 'Fire Punch', '50', 'Water x2', 'None', 2, 12, 3),
(80, 'Pinsir', 3, 1, 'Strong pincers crush foes effortlessly.', 'Guillotine', '60', 'Fire x2', 'Grass -20', 3, 57, 3),
(110, 'Lapras', 2, 1, 'Transports people across the seas.', 'Ice Beam', '90', 'Electric x2', 'Fire -20', 2, 22, 3),
(90, 'Snorlax', 7, 1, 'Its stomach can digest anything.', 'Tackle', '70', 'Fighting x2', 'None', 4, 44, 3),
(50, 'Ditto', 7, 1, 'Can transform into any Pokémon.', 'Transform', '-', 'Fighting x2', 'None', 1, 35, 2),
(50, 'Dratini', 1, 1, 'Lives in oceans and lakes.', 'Wrap', '30', 'Ice x2', 'None', 2, 24, 1),
(80, 'Charizard X', 1, 2, 'A rare evolution that changes its color.', 'Blaze Strike', '120', 'Water x2', 'None', 3, 1, 1),
(90, 'Mewtwo', 5, 2, 'Created by recombining DNA from Mew.', 'Psychic', '100', 'Darkness x2', 'None', 2, 51, 3);
