INSERT INTO tbl_cards (hp, name, type_id, stage_id, info, attack, damage, weak, resist, retreat, cardNumberInCollection, collection_id)
VALUES 
(70, 'Arcanine', 1, 2, 'A legendary Pokémon in some regions.', 'Flamethrower', '90', 'Water x2', 'None', 2, 6, 1),
(60, 'Starmie', 2, 2, 'The center of its body shines brightly.', 'Water Gun', '60', 'Electric x2', 'None', 1, 64, 2),
(50, 'Meowth', 7, 1, 'Loves shiny objects and collects coins.', 'Pay Day', '20', 'Fighting x2', 'None', 1, 56, 3),
(90, 'Raichu', 4, 2, 'Stores electricity in its cheeks.', 'Thunder', '100', 'Fighting x2', 'None', 1, 26, 3),
(80, 'Venusaur', 3, 2, 'Its flower spreads a soothing aroma.', 'Solar Beam', '90', 'Fire x2', 'Water -20', 3, 15, 1),
(70, 'Fearow', 7, 2, 'Darts around at high speed.', 'Drill Peck', '60', 'Electric x2', 'None', 1, 8, 2),
(50, 'Hitmonlee', 6, 1, 'Kicks faster than the eye can follow.', 'High Jump Kick', '50', 'Psychic x2', 'None', 0, 58, 3),
(100, 'Hitmonchan', 6, 1, 'Punches with incredible speed.', 'Jab', '70', 'Psychic x2', 'None', 0, 24, 3),
(90, 'Pidgeot', 7, 2, 'Its wings spread wide as it flies.', 'Wing Attack', '70', 'Electric x2', 'None', 1, 18, 1),
(40, 'Spearow', 7, 1, 'Eats bugs to survive.', 'Peck', '10', 'Electric x2', 'None', 1, 3, 1),
(50, 'Gastly', 5, 1, 'Can envelop an opponent entirely.', 'Lick', '10', 'Psychic x2', 'None', 0, 45, 2),
(70, 'Hypno', 5, 2, 'Puts foes to sleep with its hypnotic powers.', 'Hypnosis', '60', 'Darkness x2', 'None', 2, 48, 3),
(80, 'Machamp', 6, 2, 'Four powerful arms can throw foes.', 'Submission', '80', 'Psychic x2', 'None', 3, 20, 3),
(50, 'Sandshrew', 6, 1, 'Hides under the sand to stay cool.', 'Sand Attack', '20', 'Water x2', 'None', 1, 56, 1),
(90, 'Magneton', 4, 2, 'Generates powerful electric waves.', 'Zap Cannon', '70', 'Fighting x2', 'None', 1, 82, 2),
(80, 'Rapidash', 1, 2, 'Its hooves are said to be faster than wind.', 'Flare Blitz', '70', 'Water x2', 'None', 1, 12, 2),
(70, 'Seel', 2, 1, 'A playful swimmer with a sleek body.', 'Aqua Jet', '30', 'Electric x2', 'None', 1, 31, 2),
(90, 'Golem', 6, 2, 'Can roll down mountains at great speeds.', 'Rock Slide', '80', 'Water x2', 'Electric -20', 4, 35, 2),
(80, 'Tangela', 3, 1, 'Covered in vines.', 'Bind', '40', 'Fire x2', 'None', 2, 57, 2),
(60, 'Doduo', 7, 1, 'Can run faster than it can fly.', 'Double Kick', '20', 'Electric x2', 'None', 1, 41, 2),
(100, 'Dragonite', 1, 2, 'A mythical dragon that soars across oceans.', 'Dragon Tail', '100', 'Ice x2', 'None', 3, 46, 1),
(110, 'Electrode', 4, 2, 'Often self-destructs in battle